package api

import (
	"path/filepath"
	"strings"

	"github.com/ChengYen-Tang/glassnode-crawler/modules"
)

func SetPointInTimeApi(tc *modules.TaskController, rootFolder *string) {
	folder := filepath.Join(*rootFolder, "Point-In-Time")

	btcSymbol := "BTC"
	ethSymbol := "ETH"
	symbols := []string{btcSymbol, ethSymbol}
	exange1 := strings.Split("bigone, binance, bitfinex, bitget, bithumb, bitmex, bitstamp, bittrex, bybit, cobinhood, coinbase, coincheck, coinex, crypto.com, deribit, ftx, gate.io, gemini, hitbtc, huobi, korbit, kraken, kucoin, luno, nexo, okex, poloniex, swissborg, zb.com", ", ")
	exange2 := strings.Split("bibox, bigone, binance, bitfinex, bitget, bithumb, bitmex, bitstamp, bittrex, bybit, cobinhood, coinbase, coincheck, coinex, crypto.com, deribit, ftx, gate.io, gemini, hitbtc, huobi, korbit, kraken, kucoin, luno, nexo, okex, poloniex, swissborg, zb.com", ", ")
	exange3 := strings.Split("binance, bitfinex, bitget, bithumb, bitmex, bitstamp, bittrex, bybit, coinbase, coincheck, coinex, crypto.com, deribit, ftx, gate.io, gemini, hitbtc, huobi, korbit, kraken, kucoin, luno, okex, poloniex", ", ")
	miners1 := [...]string{"other", "1THash&58COIN", "AntPool", "ArkPool", "BinancePool", "BitFury", "BitMinter", "Bixin", "BTC.com", "BTC.TOP", "DPool", "F2Pool", "FoundryUSAPool", "Genesis", "HuobiPool", "KuCoinPool", "Lubian.com", "LuxorTech", "MaraPool", "NovaBlock", "OKExPool", "Patoshi", "PegaPool", "Poolin", "SBICrypto", "SigmaPool", "SlushPool", "SpiderPool", "TerraPool", "UKRPool", "Ultimus", "ViaBTC"}

	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/addresses/accumulation_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/addresses/accumulation_balance_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/accumulation_trend_score_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/active_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/apac_1y_supply_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/bridges/deposits_by_chain_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/bridges/net_volume_by_chain_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_bridges_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_bridges_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/bridges/total_value_locked_by_chain_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/bridges/total_value_locked_by_chain_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/bridges/withdrawals_by_chain_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_from_coinjoins_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_from_coinjoins_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_defi_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_defi_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	for _, symbol := range symbols {
		tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/addresses/sending_to_exchanges_count_pit?a=%s&i=1h&f=CSV", &folder, &symbol, false)
		for _, exange := range exange1 {
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/distribution/balance_exchanges_relative_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, false)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/distribution/balance_exchanges_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
		}
		for _, exange := range exange2 {
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_to_exchanges_count_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, false)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_to_exchanges_mean_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_to_exchanges_sum_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/distribution/exchange_net_position_change_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_exchanges_net_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_from_exchanges_mean_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_from_exchanges_sum_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_from_exchanges_count_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, false)
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_within_exchanges_sum_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &symbol, &exange, true)
		}
		for _, exange := range exange3 {
			tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_exchanges_net_by_size_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &symbol, &exange, true)
		}
		tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/exchanges_relative_pit?a=%s&i=1h&f=CSV", &folder, &symbol, false)
		tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/exchanges_mean_pit?a=%s&i=1h&f=CSV", &folder, &symbol, true)
		tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/exchanges_sum_pit?a=%s&i=1h&f=CSV", &folder, &symbol, true)
		tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/addresses/receiving_from_exchanges_count_pit?a=%s&i=1h&f=CSV", &folder, &symbol, false)
	}
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/net_growth_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_distribution_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cyd_account_based_supply_adjusted_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cdd90_account_based_age_adjusted_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/asol_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cdd_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cyd_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/dormancy_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/dormancy_flow_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/liveliness_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/asol_lth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cdd_lth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/dormancy_lth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_lth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_lth_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_lth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_lth_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_lth_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_lth_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_lth_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/nupl_more_155_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_lth_sth_profit_loss_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/msol_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/mvrv_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/net_unrealized_profit_loss_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/nvt_entity_adjusted_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/rcap_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/asol_sth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/cdd_sth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/dormancy_sth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/sopr_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svab_entity_adjusted_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_24h_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_more_10y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_1d_1w_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_1m_3m_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_1w_1m_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_1y_2y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_2y_3y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_3m_6m_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_3y_5y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_5y_7y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_6m_12m_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/svl_entity_adjusted_7y_10y_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_sth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_loss_sth_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_sth_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_sth_to_exchanges_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_sth_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_sth_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_from_sth_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/nupl_less_155_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/entity_adjusted_count_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/unrealized_loss_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/unrealized_profit_account_based_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/urpd_entity_adjusted_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_mean_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_median_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_entity_adjusted_sum_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_erc20_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_erc20_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/eth2/deposited_by_provider_volume_sum_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/emea_1y_supply_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_bridges_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_bridges_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_defi_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_defi_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_erc20_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_erc20_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_nfts_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_nfts_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_stablecoins_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_stablecoins_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/tx_types_breakdown_sum_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/tx_types_breakdown_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_vanilla_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/fees/gas_used_sum_vanilla_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/gini_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/herfindahl_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/highly_liquid_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/illiquid_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/illiquid_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/liquid_illiquid_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/liquid_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/liquid_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_lth_to_exchanges_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_lth_to_exchanges_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/lth_net_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/lth_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/lth_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/lth_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_lth_to_exchanges_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_lth_sth_to_exchanges_profit_loss_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	for _, miner := range miners1 {
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/distribution/balance_miners_sum_pit?a=%s&miner=%s&i=24h&f=CSV", &folder, &btcSymbol, &miner, false)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_to_miners_count_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, false)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_to_miners_sum_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_miners_net_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_from_miners_sum_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_from_miners_count_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, false)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/mining/volume_mined_sum_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/mining/revenue_sum_pit?a=%s&miner=%s&i=1h&f=CSV", &folder, &btcSymbol, &miner, true)
	}
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_miners_all_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_miners_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	for _, exange := range exange3 {
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_miners_to_exchanges_pit?a=%s&e=%s&i=1h&f=CSV", &folder, &btcSymbol, &exange, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_miners_to_exchanges_all_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &btcSymbol, &exange, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_whales_to_exchanges_count_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &btcSymbol, &exange, false)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_whales_to_exchanges_sum_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &btcSymbol, &exange, true)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_exchanges_to_whales_count_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &btcSymbol, &exange, false)
		tc.GetAPIInfoTwoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_exchanges_to_whales_sum_pit?a=%s&e=%s&i=24h&f=CSV", &folder, &btcSymbol, &exange, true)
	}
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_mtgox_trustee_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/new_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_nft_marketplaces_count_all_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_nft_marketplaces_volume_sum_all_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_nfts_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_nfts_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/min_1k_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_otc_desks_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_to_otc_desks_count_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_to_otc_desks_sum_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_from_otc_desks_sum_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_from_otc_desks_count_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/profit_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/receiving_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/lth_sth_profit_loss_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_loss_lth_sth_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/indicators/realized_profit_loss_lth_sth_to_exchanges_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_by_size_entity_adjusted_relative_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/sending_count_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_sth_to_exchanges_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_sth_to_exchanges_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/sth_profit_loss_ratio_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/sth_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/sth_loss_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/sth_profit_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_sth_to_exchanges_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, true)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_stablecoins_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_stablecoins_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_less_0001_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_more_100k_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_0001_001_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_001_01_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_01_1_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_1_10_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_10_100_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_100_1k_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_10k_100k_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/entities/supply_balance_1k_10k_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/supply_contracts_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_1pct_holders_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_volume_by_size_entity_adjusted_sum_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/tx_types_breakdown_count_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/tx_types_breakdown_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/supply/amer_1y_supply_change_pit?a=%s&i=24h&f=CSV", &folder, &btcSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_vanilla_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/transactions/transfers_count_vanilla_relative_pit?a=%s&i=24h&f=CSV", &folder, &ethSymbol, false)
	tc.GetAPIInfoTag("https://api.glassnode.com/v1/metrics/distribution/balance_wbtc_pit?a=%s&i=1h&f=CSV", &folder, &btcSymbol, true)
}
